---
platform: linux

inputs:
- name: spring-music

image_resource:
  type: docker-image
  source: {repository: openjdk, tag: 8-slim}

run:
  path: spring-music/ci/tasks/build.sh

caches:
  - path: .gradle/
  - path: .m2/
  - path: .ivy/
